Added wstETH:ETH price pulling

diff --git a/libexec/setzer/setzer-x-price b/libexec/setzer/setzer-x-price
--- a/libexec/setzer/setzer-x-price
+++ b/libexec/setzer/setzer-x-price
@@ -68,6 +68,44 @@ case $src in
     json=$(curl -sS "https://min-api.cryptocompare.com/data/price?fsym=${base^^}&tsyms=${quote^^}")
     setzer --format "$(jshon <<<"$json" -e USD -u)"
   };;
+  curve) {
+    ten_to_18=$(printf '%064X' 1000000000000000000) # 10^18 left-padded to 32 bytes
+    case "${pair^^}" in
+      WSTETHETH) {
+        crv_contract_addr=DC24316b9AE028F1497c275EB9192a3Ea0f67022 # stETH/ETH pool
+        crv_src_token=$(printf '%064X' 1) # stETH index
+        crv_dst_token=$(printf '%064X' 0) # ETH index
+        crv_src_amount=$ten_to_18
+      };;
+      *) {
+        echo >&2 "Error: pair not supported for Curve exchange: $pair"
+      };;
+    esac
+    # keccak256("get_dy(int128,int128,uint256)")
+    get_dy_method_id=5e0d443f
+    crv_dst_amount=$(setzer \
+      --eth-call \
+      "$crv_contract_addr" \
+      "$get_dy_method_id" \
+      "$crv_src_token$crv_dst_token$crv_src_amount"
+    )
+    case "${pair^^}" in
+      WSTETHETH) {
+        # wstETH is a non-rebasing wrapper that exposes the underlying stETH shares
+        wsteth_contract_addr=7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0
+        # keccak256("stEthPerToken()")
+        steth_per_token_method_id=035faf82
+        # how many stETH wei one would receive by unwarpping 10^18 wstETH wei
+        steth_per_wsteth=$(setzer --eth-call "$wsteth_contract_addr" "$steth_per_token_method_id")
+        # wstethEthPrice = stethPerWsteth * stethEthPrice
+        price=$(bc -l <<<"ibase=16; (${steth_per_wsteth^^} * ${crv_dst_amount^^}) / (${crv_src_amount^^} * ${ten_to_18^^})")
+      };;
+      *) {
+        price=$(bc -l <<<"ibase=16; ${crv_dst_amount^^} / ${crv_src_amount^^}")
+      };;
+    esac
+    setzer --format "$price"
+  };;
   ddex) {
     json=$(curl -sS "https://api.ddex.io/v4/markets/${base^^}-${quote^^}")
     setzer --format "$(jshon <<<"$json" -e data -e market -e lastPrice -u)"
