combine ethusd prices

diff --git a/libexec/setzer/setzer-price-ethusd b/libexec/setzer/setzer-price-ethusd
--- a/libexec/setzer/setzer-price-ethusd
+++ b/libexec/setzer/setzer-price-ethusd
@@ -1,3 +1,50 @@
 #!/usr/bin/env bash
 set -e
-setzer price eth
+
+sources=(
+  binance
+  bitfinex
+  bitstamp
+  coinbase
+  gemini
+  kraken
+)
+
+case $1 in
+  binance) {
+    ethbtc=$(setzer x-price $1 ethbtc)
+    echo "ETHBTC: $ethbtc"
+    # TODO - btc median
+    # json=$(curl -sS "https://www.binance.com/api/v3/ticker/price?symbol=ETHBTC")
+    # eth_btc=$(jshon <<<"$json" -e price -u)
+    # eth_btc=$(printf "%.10f" "$eth_btc")
+    # btc_usd=$(setzer price btc)
+    # bc <<<"$eth_btc * $btc_usd" | awk '{printf "%.10f", $0}'
+  };;
+  bitfinex) {
+    eth_usdt=$(setzer x-price $1 ethusd)
+    usdt_usd=$(setzer x-price cmc usdtusd)
+    printf "%.10f\n" $(bc -l <<<"$eth_usdt * $usdt_usd")
+  };;
+  bitstamp|coinbase|gemini|kraken) {
+    setzer x-price $1 ethusd
+  };;
+  median) {
+    for x in "${sources[@]}"; do
+      price=$(timeout 5 setzer x-price $x ethusd 2> /dev/null || true)
+      if [[ $price ]]; then
+        if [[ $price =~ ^[+-]?[0-9]+\.?[0-9]*$  ]]; then
+          prices+=( "$price" )
+        fi
+      fi
+    done
+    if [[ ${#prices[@]} -lt 3 ]]; then
+      echo "Error: not enough sources to provide a median"
+      exit 1
+    fi
+    tr " " "\\n" <<< "${prices[@]}" | datamash median 1
+  };;
+  *) {
+    setzer price $1 ethusd median
+  };;
+esac
